on: issue_comment

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - run: |
          go get github.com/google/ent/cmd/indexer
      - run: |
          indexer --help
      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"
