on: issue_comment

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - run: |
          go version
          go install github.com/google/ent/cmd/indexer@latest
      - env:
          URL: ${{ github.event.comment.body }}
        run: |
          indexer get --index=. --url="$URL"
      - run: |
        curl \
          -X POST \
          -H 'Accept: application/vnd.github.v3+json. \
          '${{ github.event.comment.url} }}/reactions' \
          -d '{"content":"+1"}'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
